package main

//go:generate file2byteslice -package=images -input=./images/spider.png -output=./images/spider.go -var=Spider_png
//go:generate file2byteslice -package=images -input=./images/spider_female.png -output=./images/spider_female.go -var=Spider_female_png
//go:generate file2byteslice -package=images -input=./images/runner.png -output=./images/runner.go -var=Runner_png
//go:generate file2byteslice -package=images -input=./images/tiles.png -output=./images/tiles.go -var=Tiles_png
//go:generate file2byteslice -package=images -input=./images/snail.png -output=./images/snail.go -var=Snail_png
//go:generate file2byteslice -package=images -input=./images/cobra.png -output=./images/cobra.go -var=Cobra_png
//go:generate file2byteslice -package=images -input=./images/cobra_male.png -output=./images/cobra_male.go -var=Cobra_male_png
//go:generate file2byteslice -package=images -input=./images/worm.png -output=./images/worm.go -var=Worm_png
//go:generate file2byteslice -package=images -input=./images/heart.png -output=./images/heart.go -var=Heart_png
//go:generate file2byteslice -package=images -input=./images/crown.png -output=./images/crown.go -var=Crown_png
//go:generate file2byteslice -package=images -input=./images/burger.png -output=./images/burger.go -var=Burger_png
//go:generate file2byteslice -package=images -input=./images/wing.png -output=./images/wing.go -var=Wing_png
//go:generate file2byteslice -package=images -input=./images/grass1.png -output=./images/grass1.go -var=Grass1_png
//go:generate file2byteslice -package=images -input=./images/grass2.png -output=./images/grass2.go -var=Grass2_png
//go:generate file2byteslice -package=images -input=./images/grass3.png -output=./images/grass3.go -var=Grass3_png
//go:generate file2byteslice -package=images -input=./images/grass4.png -output=./images/grass4.go -var=Grass4_png
//go:generate file2byteslice -package=images -input=./images/scarab.png -output=./images/scarab.go -var=Scarab_png
//go:generate file2byteslice -package=images -input=./images/mushroom.png -output=./images/mushroom.go -var=Mushroom_png
//go:generate file2byteslice -package=images -input=./images/pHerbe1.png -output=./images/pHerbe1.go -var=PHerbe1_png
//go:generate file2byteslice -package=images -input=./images/pHerbe2.png -output=./images/pHerbe2.go -var=PHerbe2_png
//go:generate file2byteslice -package=images -input=./images/pHerbe3.png -output=./images/pHerbe3.go -var=PHerbe3_png
//go:generate file2byteslice -package=images -input=./images/sGrass1.png -output=./images/sGrass1.go -var=SGrass1_png
//go:generate file2byteslice -package=images -input=./images/sGrass2.png -output=./images/sGrass2.go -var=SGrass2_png
//go:generate file2byteslice -package=images -input=./images/sGrass3.png -output=./images/sGrass3.go -var=SGrass3_png
//go:generate file2byteslice -package=images -input=./images/sGrass4.png -output=./images/sGrass4.go -var=SGrass4_png
//go:generate file2byteslice -package=images -input=./images/sGrass5.png -output=./images/sGrass5.go -var=SGrass5_png
//go:generate file2byteslice -package=images -input=./images/sGrass6.png -output=./images/sGrass6.go -var=SGrass6_png
//go:generate file2byteslice -package=images -input=./images/sGrass7.png -output=./images/sGrass7.go -var=SGrass7_png
//go:generate file2byteslice -package=images -input=./images/sGrass8.png -output=./images/sGrass8.go -var=SGrass8_png
//go:generate file2byteslice -package=images -input=./images/sGrass9.png -output=./images/sGrass9.go -var=SGrass9_png
//go:generate file2byteslice -package=images -input=./images/baozi2.png -output=./images/baozi2.go -var=Baozi2_png
//go:generate file2byteslice -package=images -input=./images/seed1.png -output=./images/seed1.go -var=Seed1_png
//go:generate file2byteslice -package=images -input=./images/button_unpressed.png -output=./images/button_unpressed.go -var=ButtonUnpressed_png
//go:generate file2byteslice -package=images -input=./images/button_pressed.png -output=./images/button_pressed.go -var=ButtonPressed_png
//go:generate file2byteslice -package=images -input=./images/sidebar.png -output=./images/sidebar.go -var=SideBar_png
//go:generate file2byteslice -package=images -input=./images/fire.png -output=./images/fire.go -var=Fire_png
//go:generate file2byteslice -package=images -input=./images/rain.png -output=./images/rain.go -var=Rain_png
//go:generate file2byteslice -package=images -input=./images/fog.png -output=./images/fog.go -var=Fog_png
//go:generate file2byteslice -package=images -input=./images/thunder.png -output=./images/thunder.go -var=Thunder_png
